# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e56f014cb0f4882b08ee7f59b7c08f70eaac293c998fde3bc2032ffb8d371cdd8234faef088b520fd5ac8e025c5394047ec4d7a005e041e807d2eafa1c929020

test:
  secret_key_base: d519c997e0ba08f10b54000e25d366490aac68631ef9a27bbb1b0d65b7e76cc3d8fbcc4de9c318330656752c0fcbdad8a9d95cec98ae6ada9ab6fde0b6513cc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
